const Teacher = [
  {
    id: 1,
    name: "teacher",
    email: "teacher@gmail.com",
    password: "123456",
    school: "Gov schoool",
    class: "12",
    type: 1,
    fatherName: "father Name",
    MotherName: "MotherName",
    mobile: "7878787878",
    status: "0",
  },
  {
    id: 2,
    name: "teacher 2",
    email: "teacher2@gmail.com",
    password: "123456",
    school: "Gov schoool",
    type: 1,
    class: "12",
    fatherName: "father Name",
    MotherName: "MotherName",
    mobile: "7878787878",
    status: "1",
  },
  {
    id: 3,
    name: "Student",
    email: "student@gmail.com",
    password: "123456",
    class: "11",
    type: 2,
    subject: "maths",

    fatherName: "father Name",
    mobile: "7878787878",
    MotherName: "MotherName",
    status: "0",
  },
  {
    id: 4,
    name: "Student 2",
    email: "student2@gmail.com",
    password: "123456",
    class: "11",
    subject: "maths",
    type: 2,
    mobile: "7878787878",
    fatherName: "father Name",
    MotherName: "MotherName",
    status: "1",
  },
];

export default Teacher;
